// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: version/version.proto

package versionpb

import (
	common "github.com/anychat/server/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_IOS         Platform = 1
	Platform_PLATFORM_ANDROID     Platform = 2
	Platform_PLATFORM_PC          Platform = 3
	Platform_PLATFORM_WEB         Platform = 4
	Platform_PLATFORM_H5          Platform = 5
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_IOS",
		2: "PLATFORM_ANDROID",
		3: "PLATFORM_PC",
		4: "PLATFORM_WEB",
		5: "PLATFORM_H5",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_IOS":         1,
		"PLATFORM_ANDROID":     2,
		"PLATFORM_PC":          3,
		"PLATFORM_WEB":         4,
		"PLATFORM_H5":          5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_version_version_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_version_version_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{0}
}

type ReleaseType int32

const (
	ReleaseType_RELEASE_TYPE_UNSPECIFIED ReleaseType = 0
	ReleaseType_RELEASE_TYPE_STABLE      ReleaseType = 1
	ReleaseType_RELEASE_TYPE_BETA        ReleaseType = 2
	ReleaseType_RELEASE_TYPE_ALPHA       ReleaseType = 3
)

// Enum value maps for ReleaseType.
var (
	ReleaseType_name = map[int32]string{
		0: "RELEASE_TYPE_UNSPECIFIED",
		1: "RELEASE_TYPE_STABLE",
		2: "RELEASE_TYPE_BETA",
		3: "RELEASE_TYPE_ALPHA",
	}
	ReleaseType_value = map[string]int32{
		"RELEASE_TYPE_UNSPECIFIED": 0,
		"RELEASE_TYPE_STABLE":      1,
		"RELEASE_TYPE_BETA":        2,
		"RELEASE_TYPE_ALPHA":       3,
	}
)

func (x ReleaseType) Enum() *ReleaseType {
	p := new(ReleaseType)
	*p = x
	return p
}

func (x ReleaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReleaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_version_version_proto_enumTypes[1].Descriptor()
}

func (ReleaseType) Type() protoreflect.EnumType {
	return &file_version_version_proto_enumTypes[1]
}

func (x ReleaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReleaseType.Descriptor instead.
func (ReleaseType) EnumDescriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{1}
}

type VersionStatus int32

const (
	VersionStatus_VERSION_STATUS_UNSPECIFIED VersionStatus = 0
	VersionStatus_VERSION_STATUS_DRAFT       VersionStatus = 1
	VersionStatus_VERSION_STATUS_PUBLISHED   VersionStatus = 2
	VersionStatus_VERSION_STATUS_ARCHIVED    VersionStatus = 3
)

// Enum value maps for VersionStatus.
var (
	VersionStatus_name = map[int32]string{
		0: "VERSION_STATUS_UNSPECIFIED",
		1: "VERSION_STATUS_DRAFT",
		2: "VERSION_STATUS_PUBLISHED",
		3: "VERSION_STATUS_ARCHIVED",
	}
	VersionStatus_value = map[string]int32{
		"VERSION_STATUS_UNSPECIFIED": 0,
		"VERSION_STATUS_DRAFT":       1,
		"VERSION_STATUS_PUBLISHED":   2,
		"VERSION_STATUS_ARCHIVED":    3,
	}
)

func (x VersionStatus) Enum() *VersionStatus {
	p := new(VersionStatus)
	*p = x
	return p
}

func (x VersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_version_version_proto_enumTypes[2].Descriptor()
}

func (VersionStatus) Type() protoreflect.EnumType {
	return &file_version_version_proto_enumTypes[2]
}

func (x VersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionStatus.Descriptor instead.
func (VersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{2}
}

// CheckVersionRequest 版本检测请求
type CheckVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"` // 平台
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                  // 当前版本号，如 1.0.0
	BuildNumber   int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`      // 构建号（iOS/Android）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionRequest) Reset() {
	*x = CheckVersionRequest{}
	mi := &file_version_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionRequest) ProtoMessage() {}

func (x *CheckVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionRequest.ProtoReflect.Descriptor instead.
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{0}
}

func (x *CheckVersionRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *CheckVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

// CheckVersionResponse 版本检测响应
type CheckVersionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasUpdate         bool                   `protobuf:"varint,1,opt,name=has_update,json=hasUpdate,proto3" json:"has_update,omitempty"`
	LatestVersion     string                 `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	LatestBuildNumber int32                  `protobuf:"varint,3,opt,name=latest_build_number,json=latestBuildNumber,proto3" json:"latest_build_number,omitempty"`
	ForceUpdate       bool                   `protobuf:"varint,4,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	MinVersion        string                 `protobuf:"bytes,5,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber    int32                  `protobuf:"varint,6,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	UpdateInfo        *UpdateInfo            `protobuf:"bytes,7,opt,name=update_info,json=updateInfo,proto3" json:"update_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckVersionResponse) Reset() {
	*x = CheckVersionResponse{}
	mi := &file_version_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionResponse) ProtoMessage() {}

func (x *CheckVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionResponse.ProtoReflect.Descriptor instead.
func (*CheckVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{1}
}

func (x *CheckVersionResponse) GetHasUpdate() bool {
	if x != nil {
		return x.HasUpdate
	}
	return false
}

func (x *CheckVersionResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *CheckVersionResponse) GetLatestBuildNumber() int32 {
	if x != nil {
		return x.LatestBuildNumber
	}
	return 0
}

func (x *CheckVersionResponse) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *CheckVersionResponse) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *CheckVersionResponse) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *CheckVersionResponse) GetUpdateInfo() *UpdateInfo {
	if x != nil {
		return x.UpdateInfo
	}
	return nil
}

// UpdateInfo 更新信息
type UpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	mi := &file_version_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UpdateInfo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// GetLatestVersionRequest 获取最新版本请求
type GetLatestVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	ReleaseType   ReleaseType            `protobuf:"varint,2,opt,name=release_type,json=releaseType,proto3,enum=anychat.version.ReleaseType" json:"release_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVersionRequest) Reset() {
	*x = GetLatestVersionRequest{}
	mi := &file_version_version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVersionRequest) ProtoMessage() {}

func (x *GetLatestVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestVersionRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *GetLatestVersionRequest) GetReleaseType() ReleaseType {
	if x != nil {
		return x.ReleaseType
	}
	return ReleaseType_RELEASE_TYPE_UNSPECIFIED
}

// GetLatestVersionResponse 获取最新版本响应
type GetLatestVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *VersionInfo           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVersionResponse) Reset() {
	*x = GetLatestVersionResponse{}
	mi := &file_version_version_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVersionResponse) ProtoMessage() {}

func (x *GetLatestVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVersionResponse.ProtoReflect.Descriptor instead.
func (*GetLatestVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestVersionResponse) GetVersion() *VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

// VersionInfo 版本信息
type VersionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform       Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber    int32                  `protobuf:"varint,4,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	VersionCode    int32                  `protobuf:"varint,5,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinVersion     string                 `protobuf:"bytes,6,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber int32                  `protobuf:"varint,7,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	ForceUpdate    bool                   `protobuf:"varint,8,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ReleaseType    ReleaseType            `protobuf:"varint,9,opt,name=release_type,json=releaseType,proto3,enum=anychat.version.ReleaseType" json:"release_type,omitempty"`
	Status         VersionStatus          `protobuf:"varint,16,opt,name=status,proto3,enum=anychat.version.VersionStatus" json:"status,omitempty"`
	Title          string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl    string                 `protobuf:"bytes,12,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize       int64                  `protobuf:"varint,13,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash       string                 `protobuf:"bytes,14,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	PublishedAt    string                 `protobuf:"bytes,15,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_version_version_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{5}
}

func (x *VersionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionInfo) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *VersionInfo) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *VersionInfo) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *VersionInfo) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *VersionInfo) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *VersionInfo) GetReleaseType() ReleaseType {
	if x != nil {
		return x.ReleaseType
	}
	return ReleaseType_RELEASE_TYPE_UNSPECIFIED
}

func (x *VersionInfo) GetStatus() VersionStatus {
	if x != nil {
		return x.Status
	}
	return VersionStatus_VERSION_STATUS_UNSPECIFIED
}

func (x *VersionInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VersionInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VersionInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *VersionInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *VersionInfo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *VersionInfo) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

// ListVersionsRequest 获取版本列表请求
type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	ReleaseType   ReleaseType            `protobuf:"varint,2,opt,name=release_type,json=releaseType,proto3,enum=anychat.version.ReleaseType" json:"release_type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_version_version_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{6}
}

func (x *ListVersionsRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *ListVersionsRequest) GetReleaseType() ReleaseType {
	if x != nil {
		return x.ReleaseType
	}
	return ReleaseType_RELEASE_TYPE_UNSPECIFIED
}

func (x *ListVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListVersionsResponse 获取版本列表响应
type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Versions      []*VersionInfo         `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_version_version_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{7}
}

func (x *ListVersionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVersionsResponse) GetVersions() []*VersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

// CreateVersionRequest 创建版本请求
type CreateVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber    int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	VersionCode    int32                  `protobuf:"varint,4,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinVersion     string                 `protobuf:"bytes,5,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber int32                  `protobuf:"varint,6,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	ForceUpdate    bool                   `protobuf:"varint,7,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ReleaseType    ReleaseType            `protobuf:"varint,8,opt,name=release_type,json=releaseType,proto3,enum=anychat.version.ReleaseType" json:"release_type,omitempty"`
	Title          string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl    string                 `protobuf:"bytes,11,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize       int64                  `protobuf:"varint,12,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash       string                 `protobuf:"bytes,13,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_version_version_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVersionRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *CreateVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *CreateVersionRequest) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *CreateVersionRequest) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *CreateVersionRequest) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *CreateVersionRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *CreateVersionRequest) GetReleaseType() ReleaseType {
	if x != nil {
		return x.ReleaseType
	}
	return ReleaseType_RELEASE_TYPE_UNSPECIFIED
}

func (x *CreateVersionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVersionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateVersionRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CreateVersionRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateVersionRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// CreateVersionResponse 创建版本响应
type CreateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	mi := &file_version_version_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVersionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateVersionResponse) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *CreateVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// GetVersionRequest 获取版本详情请求
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_version_version_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{10}
}

func (x *GetVersionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetVersionResponse 获取版本详情响应
type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *VersionInfo           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_version_version_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{11}
}

func (x *GetVersionResponse) GetVersion() *VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

// DeleteVersionRequest 删除版本请求
type DeleteVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVersionRequest) Reset() {
	*x = DeleteVersionRequest{}
	mi := &file_version_version_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionRequest) ProtoMessage() {}

func (x *DeleteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVersionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ReportVersionRequest 上报版本请求
type ReportVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=anychat.version.Platform" json:"platform,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber   int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVersionRequest) Reset() {
	*x = ReportVersionRequest{}
	mi := &file_version_version_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVersionRequest) ProtoMessage() {}

func (x *ReportVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVersionRequest.ProtoReflect.Descriptor instead.
func (*ReportVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{13}
}

func (x *ReportVersionRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *ReportVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReportVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *ReportVersionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportVersionRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *ReportVersionRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

var File_version_version_proto protoreflect.FileDescriptor

const file_version_version_proto_rawDesc = "" +
	"\n" +
	"\x15version/version.proto\x12\x0fanychat.version\x1a\x13common/common.proto\"\x89\x01\n" +
	"\x13CheckVersionRequest\x125\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\"\xb8\x02\n" +
	"\x14CheckVersionResponse\x12\x1d\n" +
	"\n" +
	"has_update\x18\x01 \x01(\bR\thasUpdate\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12.\n" +
	"\x13latest_build_number\x18\x03 \x01(\x05R\x11latestBuildNumber\x12!\n" +
	"\fforce_update\x18\x04 \x01(\bR\vforceUpdate\x12\x1f\n" +
	"\vmin_version\x18\x05 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\x06 \x01(\x05R\x0eminBuildNumber\x12<\n" +
	"\vupdate_info\x18\a \x01(\v2\x1b.anychat.version.UpdateInfoR\n" +
	"updateInfo\"\x99\x01\n" +
	"\n" +
	"UpdateInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\"\x91\x01\n" +
	"\x17GetLatestVersionRequest\x125\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12?\n" +
	"\frelease_type\x18\x02 \x01(\x0e2\x1c.anychat.version.ReleaseTypeR\vreleaseType\"R\n" +
	"\x18GetLatestVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.anychat.version.VersionInfoR\aversion\"\xcb\x04\n" +
	"\vVersionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x125\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x04 \x01(\x05R\vbuildNumber\x12!\n" +
	"\fversion_code\x18\x05 \x01(\x05R\vversionCode\x12\x1f\n" +
	"\vmin_version\x18\x06 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\a \x01(\x05R\x0eminBuildNumber\x12!\n" +
	"\fforce_update\x18\b \x01(\bR\vforceUpdate\x12?\n" +
	"\frelease_type\x18\t \x01(\x0e2\x1c.anychat.version.ReleaseTypeR\vreleaseType\x126\n" +
	"\x06status\x18\x10 \x01(\x0e2\x1e.anychat.version.VersionStatusR\x06status\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\v \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\f \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\r \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x0e \x01(\tR\bfileHash\x12!\n" +
	"\fpublished_at\x18\x0f \x01(\tR\vpublishedAt\"\xbe\x01\n" +
	"\x13ListVersionsRequest\x125\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12?\n" +
	"\frelease_type\x18\x02 \x01(\x0e2\x1c.anychat.version.ReleaseTypeR\vreleaseType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"f\n" +
	"\x14ListVersionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x128\n" +
	"\bversions\x18\x02 \x03(\v2\x1c.anychat.version.VersionInfoR\bversions\"\xe9\x03\n" +
	"\x14CreateVersionRequest\x125\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\x12!\n" +
	"\fversion_code\x18\x04 \x01(\x05R\vversionCode\x12\x1f\n" +
	"\vmin_version\x18\x05 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\x06 \x01(\x05R\x0eminBuildNumber\x12!\n" +
	"\fforce_update\x18\a \x01(\bR\vforceUpdate\x12?\n" +
	"\frelease_type\x18\b \x01(\x0e2\x1c.anychat.version.ReleaseTypeR\vreleaseType\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\v \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\f \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\r \x01(\tR\bfileHash\"x\n" +
	"\x15CreateVersionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x125\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"#\n" +
	"\x11GetVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x12GetVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.anychat.version.VersionInfoR\aversion\"&\n" +
	"\x14DeleteVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe7\x01\n" +
	"\x14ReportVersionRequest\x125\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x19.anychat.version.PlatformR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion*\x80\x01\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x02\x12\x0f\n" +
	"\vPLATFORM_PC\x10\x03\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x04\x12\x0f\n" +
	"\vPLATFORM_H5\x10\x05*s\n" +
	"\vReleaseType\x12\x1c\n" +
	"\x18RELEASE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RELEASE_TYPE_STABLE\x10\x01\x12\x15\n" +
	"\x11RELEASE_TYPE_BETA\x10\x02\x12\x16\n" +
	"\x12RELEASE_TYPE_ALPHA\x10\x03*\x84\x01\n" +
	"\rVersionStatus\x12\x1e\n" +
	"\x1aVERSION_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VERSION_STATUS_DRAFT\x10\x01\x12\x1c\n" +
	"\x18VERSION_STATUS_PUBLISHED\x10\x02\x12\x1b\n" +
	"\x17VERSION_STATUS_ARCHIVED\x10\x032\x88\x05\n" +
	"\x0eVersionService\x12[\n" +
	"\fCheckVersion\x12$.anychat.version.CheckVersionRequest\x1a%.anychat.version.CheckVersionResponse\x12g\n" +
	"\x10GetLatestVersion\x12(.anychat.version.GetLatestVersionRequest\x1a).anychat.version.GetLatestVersionResponse\x12[\n" +
	"\fListVersions\x12$.anychat.version.ListVersionsRequest\x1a%.anychat.version.ListVersionsResponse\x12^\n" +
	"\rCreateVersion\x12%.anychat.version.CreateVersionRequest\x1a&.anychat.version.CreateVersionResponse\x12U\n" +
	"\n" +
	"GetVersion\x12\".anychat.version.GetVersionRequest\x1a#.anychat.version.GetVersionResponse\x12M\n" +
	"\rDeleteVersion\x12%.anychat.version.DeleteVersionRequest\x1a\x15.anychat.common.Empty\x12M\n" +
	"\rReportVersion\x12%.anychat.version.ReportVersionRequest\x1a\x15.anychat.common.EmptyB7Z5github.com/anychat/server/api/proto/version;versionpbb\x06proto3"

var (
	file_version_version_proto_rawDescOnce sync.Once
	file_version_version_proto_rawDescData []byte
)

func file_version_version_proto_rawDescGZIP() []byte {
	file_version_version_proto_rawDescOnce.Do(func() {
		file_version_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_version_proto_rawDesc), len(file_version_version_proto_rawDesc)))
	})
	return file_version_version_proto_rawDescData
}

var file_version_version_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_version_version_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_version_version_proto_goTypes = []any{
	(Platform)(0),                    // 0: anychat.version.Platform
	(ReleaseType)(0),                 // 1: anychat.version.ReleaseType
	(VersionStatus)(0),               // 2: anychat.version.VersionStatus
	(*CheckVersionRequest)(nil),      // 3: anychat.version.CheckVersionRequest
	(*CheckVersionResponse)(nil),     // 4: anychat.version.CheckVersionResponse
	(*UpdateInfo)(nil),               // 5: anychat.version.UpdateInfo
	(*GetLatestVersionRequest)(nil),  // 6: anychat.version.GetLatestVersionRequest
	(*GetLatestVersionResponse)(nil), // 7: anychat.version.GetLatestVersionResponse
	(*VersionInfo)(nil),              // 8: anychat.version.VersionInfo
	(*ListVersionsRequest)(nil),      // 9: anychat.version.ListVersionsRequest
	(*ListVersionsResponse)(nil),     // 10: anychat.version.ListVersionsResponse
	(*CreateVersionRequest)(nil),     // 11: anychat.version.CreateVersionRequest
	(*CreateVersionResponse)(nil),    // 12: anychat.version.CreateVersionResponse
	(*GetVersionRequest)(nil),        // 13: anychat.version.GetVersionRequest
	(*GetVersionResponse)(nil),       // 14: anychat.version.GetVersionResponse
	(*DeleteVersionRequest)(nil),     // 15: anychat.version.DeleteVersionRequest
	(*ReportVersionRequest)(nil),     // 16: anychat.version.ReportVersionRequest
	(*common.Empty)(nil),             // 17: anychat.common.Empty
}
var file_version_version_proto_depIdxs = []int32{
	0,  // 0: anychat.version.CheckVersionRequest.platform:type_name -> anychat.version.Platform
	5,  // 1: anychat.version.CheckVersionResponse.update_info:type_name -> anychat.version.UpdateInfo
	0,  // 2: anychat.version.GetLatestVersionRequest.platform:type_name -> anychat.version.Platform
	1,  // 3: anychat.version.GetLatestVersionRequest.release_type:type_name -> anychat.version.ReleaseType
	8,  // 4: anychat.version.GetLatestVersionResponse.version:type_name -> anychat.version.VersionInfo
	0,  // 5: anychat.version.VersionInfo.platform:type_name -> anychat.version.Platform
	1,  // 6: anychat.version.VersionInfo.release_type:type_name -> anychat.version.ReleaseType
	2,  // 7: anychat.version.VersionInfo.status:type_name -> anychat.version.VersionStatus
	0,  // 8: anychat.version.ListVersionsRequest.platform:type_name -> anychat.version.Platform
	1,  // 9: anychat.version.ListVersionsRequest.release_type:type_name -> anychat.version.ReleaseType
	8,  // 10: anychat.version.ListVersionsResponse.versions:type_name -> anychat.version.VersionInfo
	0,  // 11: anychat.version.CreateVersionRequest.platform:type_name -> anychat.version.Platform
	1,  // 12: anychat.version.CreateVersionRequest.release_type:type_name -> anychat.version.ReleaseType
	0,  // 13: anychat.version.CreateVersionResponse.platform:type_name -> anychat.version.Platform
	8,  // 14: anychat.version.GetVersionResponse.version:type_name -> anychat.version.VersionInfo
	0,  // 15: anychat.version.ReportVersionRequest.platform:type_name -> anychat.version.Platform
	3,  // 16: anychat.version.VersionService.CheckVersion:input_type -> anychat.version.CheckVersionRequest
	6,  // 17: anychat.version.VersionService.GetLatestVersion:input_type -> anychat.version.GetLatestVersionRequest
	9,  // 18: anychat.version.VersionService.ListVersions:input_type -> anychat.version.ListVersionsRequest
	11, // 19: anychat.version.VersionService.CreateVersion:input_type -> anychat.version.CreateVersionRequest
	13, // 20: anychat.version.VersionService.GetVersion:input_type -> anychat.version.GetVersionRequest
	15, // 21: anychat.version.VersionService.DeleteVersion:input_type -> anychat.version.DeleteVersionRequest
	16, // 22: anychat.version.VersionService.ReportVersion:input_type -> anychat.version.ReportVersionRequest
	4,  // 23: anychat.version.VersionService.CheckVersion:output_type -> anychat.version.CheckVersionResponse
	7,  // 24: anychat.version.VersionService.GetLatestVersion:output_type -> anychat.version.GetLatestVersionResponse
	10, // 25: anychat.version.VersionService.ListVersions:output_type -> anychat.version.ListVersionsResponse
	12, // 26: anychat.version.VersionService.CreateVersion:output_type -> anychat.version.CreateVersionResponse
	14, // 27: anychat.version.VersionService.GetVersion:output_type -> anychat.version.GetVersionResponse
	17, // 28: anychat.version.VersionService.DeleteVersion:output_type -> anychat.common.Empty
	17, // 29: anychat.version.VersionService.ReportVersion:output_type -> anychat.common.Empty
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_version_version_proto_init() }
func file_version_version_proto_init() {
	if File_version_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_version_proto_rawDesc), len(file_version_version_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_version_version_proto_goTypes,
		DependencyIndexes: file_version_version_proto_depIdxs,
		EnumInfos:         file_version_version_proto_enumTypes,
		MessageInfos:      file_version_version_proto_msgTypes,
	}.Build()
	File_version_version_proto = out.File
	file_version_version_proto_goTypes = nil
	file_version_version_proto_depIdxs = nil
}
