// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: push/push.proto

package pushpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushType 推送类型
type PushType int32

const (
	PushType_PUSH_TYPE_UNSPECIFIED     PushType = 0
	PushType_PUSH_TYPE_MESSAGE_NEW     PushType = 1
	PushType_PUSH_TYPE_MESSAGE_MENTION PushType = 2
	PushType_PUSH_TYPE_FRIEND_REQUEST  PushType = 3
	PushType_PUSH_TYPE_GROUP_INVITED   PushType = 4
	PushType_PUSH_TYPE_CALL_INVITE     PushType = 5
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "PUSH_TYPE_UNSPECIFIED",
		1: "PUSH_TYPE_MESSAGE_NEW",
		2: "PUSH_TYPE_MESSAGE_MENTION",
		3: "PUSH_TYPE_FRIEND_REQUEST",
		4: "PUSH_TYPE_GROUP_INVITED",
		5: "PUSH_TYPE_CALL_INVITE",
	}
	PushType_value = map[string]int32{
		"PUSH_TYPE_UNSPECIFIED":     0,
		"PUSH_TYPE_MESSAGE_NEW":     1,
		"PUSH_TYPE_MESSAGE_MENTION": 2,
		"PUSH_TYPE_FRIEND_REQUEST":  3,
		"PUSH_TYPE_GROUP_INVITED":   4,
		"PUSH_TYPE_CALL_INVITE":     5,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[0].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[0]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

// SendPushRequest 推送请求
type SendPushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标用户 ID 列表
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// 推送标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 推送正文
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 推送类型
	PushType PushType `protobuf:"varint,4,opt,name=push_type,json=pushType,proto3,enum=anychat.push.PushType" json:"push_type,omitempty"`
	// 附加数据（键值对），客户端根据业务处理
	Extras        map[string]string `protobuf:"bytes,5,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPushRequest) Reset() {
	*x = SendPushRequest{}
	mi := &file_push_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushRequest) ProtoMessage() {}

func (x *SendPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushRequest.ProtoReflect.Descriptor instead.
func (*SendPushRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *SendPushRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendPushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPushRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendPushRequest) GetPushType() PushType {
	if x != nil {
		return x.PushType
	}
	return PushType_PUSH_TYPE_UNSPECIFIED
}

func (x *SendPushRequest) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

// SendPushResponse 推送响应
type SendPushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成功推送的设备数
	SuccessCount int32 `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// 失败推送的设备数
	FailureCount int32 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// 极光推送消息 ID
	MsgId         string `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPushResponse) Reset() {
	*x = SendPushResponse{}
	mi := &file_push_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushResponse) ProtoMessage() {}

func (x *SendPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushResponse.ProtoReflect.Descriptor instead.
func (*SendPushResponse) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

func (x *SendPushResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SendPushResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *SendPushResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

var File_push_push_proto protoreflect.FileDescriptor

const file_push_push_proto_rawDesc = "" +
	"\n" +
	"\x0fpush/push.proto\x12\fanychat.push\"\x8f\x02\n" +
	"\x0fSendPushRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x123\n" +
	"\tpush_type\x18\x04 \x01(\x0e2\x16.anychat.push.PushTypeR\bpushType\x12A\n" +
	"\x06extras\x18\x05 \x03(\v2).anychat.push.SendPushRequest.ExtrasEntryR\x06extras\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x10SendPushResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId*\xb5\x01\n" +
	"\bPushType\x12\x19\n" +
	"\x15PUSH_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PUSH_TYPE_MESSAGE_NEW\x10\x01\x12\x1d\n" +
	"\x19PUSH_TYPE_MESSAGE_MENTION\x10\x02\x12\x1c\n" +
	"\x18PUSH_TYPE_FRIEND_REQUEST\x10\x03\x12\x1b\n" +
	"\x17PUSH_TYPE_GROUP_INVITED\x10\x04\x12\x19\n" +
	"\x15PUSH_TYPE_CALL_INVITE\x10\x052X\n" +
	"\vPushService\x12I\n" +
	"\bSendPush\x12\x1d.anychat.push.SendPushRequest\x1a\x1e.anychat.push.SendPushResponseB1Z/github.com/anychat/server/api/proto/push;pushpbb\x06proto3"

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData []byte
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)))
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_push_push_proto_goTypes = []any{
	(PushType)(0),            // 0: anychat.push.PushType
	(*SendPushRequest)(nil),  // 1: anychat.push.SendPushRequest
	(*SendPushResponse)(nil), // 2: anychat.push.SendPushResponse
	nil,                      // 3: anychat.push.SendPushRequest.ExtrasEntry
}
var file_push_push_proto_depIdxs = []int32{
	0, // 0: anychat.push.SendPushRequest.push_type:type_name -> anychat.push.PushType
	3, // 1: anychat.push.SendPushRequest.extras:type_name -> anychat.push.SendPushRequest.ExtrasEntry
	1, // 2: anychat.push.PushService.SendPush:input_type -> anychat.push.SendPushRequest
	2, // 3: anychat.push.PushService.SendPush:output_type -> anychat.push.SendPushResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		EnumInfos:         file_push_push_proto_enumTypes,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
