// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: conversation/conversation.proto

package conversationpb

import (
	context "context"
	common "github.com/anychat/server/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversationService_GetConversations_FullMethodName           = "/anychat.conversation.ConversationService/GetConversations"
	ConversationService_GetConversation_FullMethodName            = "/anychat.conversation.ConversationService/GetConversation"
	ConversationService_CreateOrUpdateConversation_FullMethodName = "/anychat.conversation.ConversationService/CreateOrUpdateConversation"
	ConversationService_DeleteConversation_FullMethodName         = "/anychat.conversation.ConversationService/DeleteConversation"
	ConversationService_SetPinned_FullMethodName                  = "/anychat.conversation.ConversationService/SetPinned"
	ConversationService_SetMuted_FullMethodName                   = "/anychat.conversation.ConversationService/SetMuted"
	ConversationService_ClearUnread_FullMethodName                = "/anychat.conversation.ConversationService/ClearUnread"
	ConversationService_GetTotalUnread_FullMethodName             = "/anychat.conversation.ConversationService/GetTotalUnread"
	ConversationService_IncrUnread_FullMethodName                 = "/anychat.conversation.ConversationService/IncrUnread"
	ConversationService_SetBurnAfterReading_FullMethodName        = "/anychat.conversation.ConversationService/SetBurnAfterReading"
	ConversationService_SetAutoDelete_FullMethodName              = "/anychat.conversation.ConversationService/SetAutoDelete"
)

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConversationService 会话管理服务
type ConversationServiceClient interface {
	// GetConversations 获取用户会话列表（支持增量同步）
	GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error)
	// GetConversation 获取单个会话详情
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	// CreateOrUpdateConversation 创建或更新会话（消息到达时由消息服务调用）
	CreateOrUpdateConversation(ctx context.Context, in *CreateOrUpdateConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	// DeleteConversation 删除会话
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetPinned 设置会话置顶/取消置顶
	SetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetMuted 设置会话免打扰/取消免打扰
	SetMuted(ctx context.Context, in *SetMutedRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// ClearUnread 清除会话未读数（标记已读）
	ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// GetTotalUnread 获取用户所有会话的总未读数
	GetTotalUnread(ctx context.Context, in *GetTotalUnreadRequest, opts ...grpc.CallOption) (*GetTotalUnreadResponse, error)
	// IncrUnread 增加会话未读数（消息到达时由消息服务调用）
	IncrUnread(ctx context.Context, in *IncrUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetBurnAfterReading 设置阅后即焚时长（秒），0表示取消
	SetBurnAfterReading(ctx context.Context, in *SetBurnAfterReadingRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetAutoDelete 设置自动删除时长（秒），0表示取消
	SetAutoDelete(ctx context.Context, in *SetAutoDeleteRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type conversationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationServiceClient(cc grpc.ClientConnInterface) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationsResponse)
	err := c.cc.Invoke(ctx, ConversationService_GetConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conversation)
	err := c.cc.Invoke(ctx, ConversationService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) CreateOrUpdateConversation(ctx context.Context, in *CreateOrUpdateConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conversation)
	err := c.cc.Invoke(ctx, ConversationService_CreateOrUpdateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_SetPinned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SetMuted(ctx context.Context, in *SetMutedRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_SetMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_ClearUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetTotalUnread(ctx context.Context, in *GetTotalUnreadRequest, opts ...grpc.CallOption) (*GetTotalUnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalUnreadResponse)
	err := c.cc.Invoke(ctx, ConversationService_GetTotalUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) IncrUnread(ctx context.Context, in *IncrUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_IncrUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SetBurnAfterReading(ctx context.Context, in *SetBurnAfterReadingRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_SetBurnAfterReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SetAutoDelete(ctx context.Context, in *SetAutoDeleteRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, ConversationService_SetAutoDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServiceServer is the server API for ConversationService service.
// All implementations must embed UnimplementedConversationServiceServer
// for forward compatibility.
//
// ConversationService 会话管理服务
type ConversationServiceServer interface {
	// GetConversations 获取用户会话列表（支持增量同步）
	GetConversations(context.Context, *GetConversationsRequest) (*GetConversationsResponse, error)
	// GetConversation 获取单个会话详情
	GetConversation(context.Context, *GetConversationRequest) (*Conversation, error)
	// CreateOrUpdateConversation 创建或更新会话（消息到达时由消息服务调用）
	CreateOrUpdateConversation(context.Context, *CreateOrUpdateConversationRequest) (*Conversation, error)
	// DeleteConversation 删除会话
	DeleteConversation(context.Context, *DeleteConversationRequest) (*common.Empty, error)
	// SetPinned 设置会话置顶/取消置顶
	SetPinned(context.Context, *SetPinnedRequest) (*common.Empty, error)
	// SetMuted 设置会话免打扰/取消免打扰
	SetMuted(context.Context, *SetMutedRequest) (*common.Empty, error)
	// ClearUnread 清除会话未读数（标记已读）
	ClearUnread(context.Context, *ClearUnreadRequest) (*common.Empty, error)
	// GetTotalUnread 获取用户所有会话的总未读数
	GetTotalUnread(context.Context, *GetTotalUnreadRequest) (*GetTotalUnreadResponse, error)
	// IncrUnread 增加会话未读数（消息到达时由消息服务调用）
	IncrUnread(context.Context, *IncrUnreadRequest) (*common.Empty, error)
	// SetBurnAfterReading 设置阅后即焚时长（秒），0表示取消
	SetBurnAfterReading(context.Context, *SetBurnAfterReadingRequest) (*common.Empty, error)
	// SetAutoDelete 设置自动删除时长（秒），0表示取消
	SetAutoDelete(context.Context, *SetAutoDeleteRequest) (*common.Empty, error)
	mustEmbedUnimplementedConversationServiceServer()
}

// UnimplementedConversationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationServiceServer struct{}

func (UnimplementedConversationServiceServer) GetConversations(context.Context, *GetConversationsRequest) (*GetConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversations not implemented")
}
func (UnimplementedConversationServiceServer) GetConversation(context.Context, *GetConversationRequest) (*Conversation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedConversationServiceServer) CreateOrUpdateConversation(context.Context, *CreateOrUpdateConversationRequest) (*Conversation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateConversation not implemented")
}
func (UnimplementedConversationServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedConversationServiceServer) SetPinned(context.Context, *SetPinnedRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPinned not implemented")
}
func (UnimplementedConversationServiceServer) SetMuted(context.Context, *SetMutedRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMuted not implemented")
}
func (UnimplementedConversationServiceServer) ClearUnread(context.Context, *ClearUnreadRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearUnread not implemented")
}
func (UnimplementedConversationServiceServer) GetTotalUnread(context.Context, *GetTotalUnreadRequest) (*GetTotalUnreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalUnread not implemented")
}
func (UnimplementedConversationServiceServer) IncrUnread(context.Context, *IncrUnreadRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrUnread not implemented")
}
func (UnimplementedConversationServiceServer) SetBurnAfterReading(context.Context, *SetBurnAfterReadingRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBurnAfterReading not implemented")
}
func (UnimplementedConversationServiceServer) SetAutoDelete(context.Context, *SetAutoDeleteRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutoDelete not implemented")
}
func (UnimplementedConversationServiceServer) mustEmbedUnimplementedConversationServiceServer() {}
func (UnimplementedConversationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConversationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServiceServer will
// result in compilation errors.
type UnsafeConversationServiceServer interface {
	mustEmbedUnimplementedConversationServiceServer()
}

func RegisterConversationServiceServer(s grpc.ServiceRegistrar, srv ConversationServiceServer) {
	// If the following call panics, it indicates UnimplementedConversationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationService_ServiceDesc, srv)
}

func _ConversationService_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversations(ctx, req.(*GetConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_CreateOrUpdateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).CreateOrUpdateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_CreateOrUpdateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).CreateOrUpdateConversation(ctx, req.(*CreateOrUpdateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SetPinned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinnedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SetPinned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SetPinned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SetPinned(ctx, req.(*SetPinnedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SetMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SetMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SetMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SetMuted(ctx, req.(*SetMutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_ClearUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).ClearUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_ClearUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).ClearUnread(ctx, req.(*ClearUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetTotalUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetTotalUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetTotalUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetTotalUnread(ctx, req.(*GetTotalUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_IncrUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).IncrUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_IncrUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).IncrUnread(ctx, req.(*IncrUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SetBurnAfterReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBurnAfterReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SetBurnAfterReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SetBurnAfterReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SetBurnAfterReading(ctx, req.(*SetBurnAfterReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SetAutoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SetAutoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SetAutoDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SetAutoDelete(ctx, req.(*SetAutoDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationService_ServiceDesc is the grpc.ServiceDesc for ConversationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anychat.conversation.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversations",
			Handler:    _ConversationService_GetConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _ConversationService_GetConversation_Handler,
		},
		{
			MethodName: "CreateOrUpdateConversation",
			Handler:    _ConversationService_CreateOrUpdateConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _ConversationService_DeleteConversation_Handler,
		},
		{
			MethodName: "SetPinned",
			Handler:    _ConversationService_SetPinned_Handler,
		},
		{
			MethodName: "SetMuted",
			Handler:    _ConversationService_SetMuted_Handler,
		},
		{
			MethodName: "ClearUnread",
			Handler:    _ConversationService_ClearUnread_Handler,
		},
		{
			MethodName: "GetTotalUnread",
			Handler:    _ConversationService_GetTotalUnread_Handler,
		},
		{
			MethodName: "IncrUnread",
			Handler:    _ConversationService_IncrUnread_Handler,
		},
		{
			MethodName: "SetBurnAfterReading",
			Handler:    _ConversationService_SetBurnAfterReading_Handler,
		},
		{
			MethodName: "SetAutoDelete",
			Handler:    _ConversationService_SetAutoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conversation/conversation.proto",
}
