// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: conversation/conversation.proto

package conversationpb

import (
	common "github.com/anychat/server/api/proto/common"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Conversation 会话
type Conversation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConversationId     string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationType   string                 `protobuf:"bytes,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // single/group/system
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId           string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 单聊为对方用户ID，群聊为群ID
	LastMessageId      string                 `protobuf:"bytes,5,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastMessageContent string                 `protobuf:"bytes,6,opt,name=last_message_content,json=lastMessageContent,proto3" json:"last_message_content,omitempty"`
	LastMessageTime    *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_message_time,json=lastMessageTime,proto3" json:"last_message_time,omitempty"`
	UnreadCount        int32                  `protobuf:"varint,8,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsPinned           bool                   `protobuf:"varint,9,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsMuted            bool                   `protobuf:"varint,10,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	PinTime            *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=pin_time,json=pinTime,proto3" json:"pin_time,omitempty"`                                     // 置顶时间（用于排序）
	BurnAfterReading   int32                  `protobuf:"varint,14,opt,name=burn_after_reading,json=burnAfterReading,proto3" json:"burn_after_reading,omitempty"`       // 阅后即焚时长(秒),0表示未启用
	AutoDeleteDuration int32                  `protobuf:"varint,15,opt,name=auto_delete_duration,json=autoDeleteDuration,proto3" json:"auto_delete_duration,omitempty"` // 自动删除时长(秒),0表示未启用
	CreatedAt          *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_conversation_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *Conversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Conversation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Conversation) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *Conversation) GetLastMessageContent() string {
	if x != nil {
		return x.LastMessageContent
	}
	return ""
}

func (x *Conversation) GetLastMessageTime() *timestamp.Timestamp {
	if x != nil {
		return x.LastMessageTime
	}
	return nil
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Conversation) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *Conversation) GetPinTime() *timestamp.Timestamp {
	if x != nil {
		return x.PinTime
	}
	return nil
}

func (x *Conversation) GetBurnAfterReading() int32 {
	if x != nil {
		return x.BurnAfterReading
	}
	return 0
}

func (x *Conversation) GetAutoDeleteDuration() int32 {
	if x != nil {
		return x.AutoDeleteDuration
	}
	return 0
}

func (x *Conversation) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetConversationsRequest 获取会话列表请求
type GetConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UpdatedBefore *int64                 `protobuf:"varint,3,opt,name=updated_before,json=updatedBefore,proto3,oneof" json:"updated_before,omitempty"` // Unix时间戳，用于增量同步（仅返回此时间之前更新的会话）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsRequest) Reset() {
	*x = GetConversationsRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsRequest) ProtoMessage() {}

func (x *GetConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetConversationsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConversationsRequest) GetUpdatedBefore() int64 {
	if x != nil && x.UpdatedBefore != nil {
		return *x.UpdatedBefore
	}
	return 0
}

// GetConversationsResponse 获取会话列表响应
type GetConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsResponse) Reset() {
	*x = GetConversationsResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsResponse) ProtoMessage() {}

func (x *GetConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsResponse.ProtoReflect.Descriptor instead.
func (*GetConversationsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *GetConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *GetConversationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// GetConversationRequest 获取单个会话请求
type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// GetConversationByUserAndTargetRequest 根据用户ID、会话类型和目标ID获取会话请求
type GetConversationByUserAndTargetRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationType string                 `protobuf:"bytes,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // single/group
	TargetId         string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConversationByUserAndTargetRequest) Reset() {
	*x = GetConversationByUserAndTargetRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationByUserAndTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationByUserAndTargetRequest) ProtoMessage() {}

func (x *GetConversationByUserAndTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationByUserAndTargetRequest.ProtoReflect.Descriptor instead.
func (*GetConversationByUserAndTargetRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationByUserAndTargetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConversationByUserAndTargetRequest) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *GetConversationByUserAndTargetRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// CreateOrUpdateConversationRequest 创建或更新会话请求
type CreateOrUpdateConversationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ConversationType     string                 `protobuf:"bytes,1,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // single/group/system
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId             string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	LastMessageId        string                 `protobuf:"bytes,4,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastMessageContent   string                 `protobuf:"bytes,5,opt,name=last_message_content,json=lastMessageContent,proto3" json:"last_message_content,omitempty"`
	LastMessageTimestamp int64                  `protobuf:"varint,6,opt,name=last_message_timestamp,json=lastMessageTimestamp,proto3" json:"last_message_timestamp,omitempty"` // Unix时间戳（秒）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrUpdateConversationRequest) Reset() {
	*x = CreateOrUpdateConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateConversationRequest) ProtoMessage() {}

func (x *CreateOrUpdateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrUpdateConversationRequest) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *CreateOrUpdateConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrUpdateConversationRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateOrUpdateConversationRequest) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *CreateOrUpdateConversationRequest) GetLastMessageContent() string {
	if x != nil {
		return x.LastMessageContent
	}
	return ""
}

func (x *CreateOrUpdateConversationRequest) GetLastMessageTimestamp() int64 {
	if x != nil {
		return x.LastMessageTimestamp
	}
	return 0
}

// DeleteConversationRequest 删除会话请求
type DeleteConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// SetPinnedRequest 设置置顶请求
type SetPinnedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Pinned         bool                   `protobuf:"varint,3,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPinnedRequest) Reset() {
	*x = SetPinnedRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPinnedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPinnedRequest) ProtoMessage() {}

func (x *SetPinnedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPinnedRequest.ProtoReflect.Descriptor instead.
func (*SetPinnedRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *SetPinnedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPinnedRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SetPinnedRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

// SetMutedRequest 设置免打扰请求
type SetMutedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Muted          bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetMutedRequest) Reset() {
	*x = SetMutedRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMutedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMutedRequest) ProtoMessage() {}

func (x *SetMutedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMutedRequest.ProtoReflect.Descriptor instead.
func (*SetMutedRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *SetMutedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetMutedRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SetMutedRequest) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

// ClearUnreadRequest 清除未读数请求
type ClearUnreadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearUnreadRequest) Reset() {
	*x = ClearUnreadRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUnreadRequest) ProtoMessage() {}

func (x *ClearUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUnreadRequest.ProtoReflect.Descriptor instead.
func (*ClearUnreadRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *ClearUnreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearUnreadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// GetTotalUnreadRequest 获取总未读数请求
type GetTotalUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalUnreadRequest) Reset() {
	*x = GetTotalUnreadRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalUnreadRequest) ProtoMessage() {}

func (x *GetTotalUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalUnreadRequest.ProtoReflect.Descriptor instead.
func (*GetTotalUnreadRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *GetTotalUnreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetTotalUnreadResponse 获取总未读数响应
type GetTotalUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUnread   int32                  `protobuf:"varint,1,opt,name=total_unread,json=totalUnread,proto3" json:"total_unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalUnreadResponse) Reset() {
	*x = GetTotalUnreadResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalUnreadResponse) ProtoMessage() {}

func (x *GetTotalUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalUnreadResponse.ProtoReflect.Descriptor instead.
func (*GetTotalUnreadResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *GetTotalUnreadResponse) GetTotalUnread() int32 {
	if x != nil {
		return x.TotalUnread
	}
	return 0
}

// IncrUnreadRequest 增加未读数请求
type IncrUnreadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Count          int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncrUnreadRequest) Reset() {
	*x = IncrUnreadRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrUnreadRequest) ProtoMessage() {}

func (x *IncrUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrUnreadRequest.ProtoReflect.Descriptor instead.
func (*IncrUnreadRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *IncrUnreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IncrUnreadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *IncrUnreadRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SetBurnAfterReadingRequest 设置阅后即焚请求
type SetBurnAfterReadingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Duration       int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"` // 秒,0表示取消
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetBurnAfterReadingRequest) Reset() {
	*x = SetBurnAfterReadingRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBurnAfterReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBurnAfterReadingRequest) ProtoMessage() {}

func (x *SetBurnAfterReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBurnAfterReadingRequest.ProtoReflect.Descriptor instead.
func (*SetBurnAfterReadingRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *SetBurnAfterReadingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetBurnAfterReadingRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SetBurnAfterReadingRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// SetAutoDeleteRequest 设置自动删除请求
type SetAutoDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Duration       int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"` // 秒,0表示取消
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetAutoDeleteRequest) Reset() {
	*x = SetAutoDeleteRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoDeleteRequest) ProtoMessage() {}

func (x *SetAutoDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoDeleteRequest.ProtoReflect.Descriptor instead.
func (*SetAutoDeleteRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *SetAutoDeleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetAutoDeleteRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SetAutoDeleteRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_conversation_conversation_proto protoreflect.FileDescriptor

const file_conversation_conversation_proto_rawDesc = "" +
	"\n" +
	"\x1fconversation/conversation.proto\x12\x14anychat.conversation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xa4\x05\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\tR\x10conversationType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12&\n" +
	"\x0flast_message_id\x18\x05 \x01(\tR\rlastMessageId\x120\n" +
	"\x14last_message_content\x18\x06 \x01(\tR\x12lastMessageContent\x12F\n" +
	"\x11last_message_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0flastMessageTime\x12!\n" +
	"\funread_count\x18\b \x01(\x05R\vunreadCount\x12\x1b\n" +
	"\tis_pinned\x18\t \x01(\bR\bisPinned\x12\x19\n" +
	"\bis_muted\x18\n" +
	" \x01(\bR\aisMuted\x125\n" +
	"\bpin_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\apinTime\x12,\n" +
	"\x12burn_after_reading\x18\x0e \x01(\x05R\x10burnAfterReading\x120\n" +
	"\x14auto_delete_duration\x18\x0f \x01(\x05R\x12autoDeleteDuration\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x87\x01\n" +
	"\x17GetConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12*\n" +
	"\x0eupdated_before\x18\x03 \x01(\x03H\x00R\rupdatedBefore\x88\x01\x01B\x11\n" +
	"\x0f_updated_before\"\x7f\n" +
	"\x18GetConversationsResponse\x12H\n" +
	"\rconversations\x18\x01 \x03(\v2\".anychat.conversation.ConversationR\rconversations\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"Z\n" +
	"\x16GetConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\x8a\x01\n" +
	"%GetConversationByUserAndTargetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\tR\x10conversationType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"\x96\x02\n" +
	"!CreateOrUpdateConversationRequest\x12+\n" +
	"\x11conversation_type\x18\x01 \x01(\tR\x10conversationType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12&\n" +
	"\x0flast_message_id\x18\x04 \x01(\tR\rlastMessageId\x120\n" +
	"\x14last_message_content\x18\x05 \x01(\tR\x12lastMessageContent\x124\n" +
	"\x16last_message_timestamp\x18\x06 \x01(\x03R\x14lastMessageTimestamp\"]\n" +
	"\x19DeleteConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"l\n" +
	"\x10SetPinnedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06pinned\x18\x03 \x01(\bR\x06pinned\"i\n" +
	"\x0fSetMutedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\"V\n" +
	"\x12ClearUnreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"0\n" +
	"\x15GetTotalUnreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x16GetTotalUnreadResponse\x12!\n" +
	"\ftotal_unread\x18\x01 \x01(\x05R\vtotalUnread\"k\n" +
	"\x11IncrUnreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"z\n" +
	"\x1aSetBurnAfterReadingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\"t\n" +
	"\x14SetAutoDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration2\x9b\b\n" +
	"\x13ConversationService\x12q\n" +
	"\x10GetConversations\x12-.anychat.conversation.GetConversationsRequest\x1a..anychat.conversation.GetConversationsResponse\x12c\n" +
	"\x0fGetConversation\x12,.anychat.conversation.GetConversationRequest\x1a\".anychat.conversation.Conversation\x12y\n" +
	"\x1aCreateOrUpdateConversation\x127.anychat.conversation.CreateOrUpdateConversationRequest\x1a\".anychat.conversation.Conversation\x12\\\n" +
	"\x12DeleteConversation\x12/.anychat.conversation.DeleteConversationRequest\x1a\x15.anychat.common.Empty\x12J\n" +
	"\tSetPinned\x12&.anychat.conversation.SetPinnedRequest\x1a\x15.anychat.common.Empty\x12H\n" +
	"\bSetMuted\x12%.anychat.conversation.SetMutedRequest\x1a\x15.anychat.common.Empty\x12N\n" +
	"\vClearUnread\x12(.anychat.conversation.ClearUnreadRequest\x1a\x15.anychat.common.Empty\x12k\n" +
	"\x0eGetTotalUnread\x12+.anychat.conversation.GetTotalUnreadRequest\x1a,.anychat.conversation.GetTotalUnreadResponse\x12L\n" +
	"\n" +
	"IncrUnread\x12'.anychat.conversation.IncrUnreadRequest\x1a\x15.anychat.common.Empty\x12^\n" +
	"\x13SetBurnAfterReading\x120.anychat.conversation.SetBurnAfterReadingRequest\x1a\x15.anychat.common.Empty\x12R\n" +
	"\rSetAutoDelete\x12*.anychat.conversation.SetAutoDeleteRequest\x1a\x15.anychat.common.EmptyBAZ?github.com/anychat/server/api/proto/conversation;conversationpbb\x06proto3"

var (
	file_conversation_conversation_proto_rawDescOnce sync.Once
	file_conversation_conversation_proto_rawDescData []byte
)

func file_conversation_conversation_proto_rawDescGZIP() []byte {
	file_conversation_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)))
	})
	return file_conversation_conversation_proto_rawDescData
}

var file_conversation_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_conversation_conversation_proto_goTypes = []any{
	(*Conversation)(nil),                          // 0: anychat.conversation.Conversation
	(*GetConversationsRequest)(nil),               // 1: anychat.conversation.GetConversationsRequest
	(*GetConversationsResponse)(nil),              // 2: anychat.conversation.GetConversationsResponse
	(*GetConversationRequest)(nil),                // 3: anychat.conversation.GetConversationRequest
	(*GetConversationByUserAndTargetRequest)(nil), // 4: anychat.conversation.GetConversationByUserAndTargetRequest
	(*CreateOrUpdateConversationRequest)(nil),     // 5: anychat.conversation.CreateOrUpdateConversationRequest
	(*DeleteConversationRequest)(nil),             // 6: anychat.conversation.DeleteConversationRequest
	(*SetPinnedRequest)(nil),                      // 7: anychat.conversation.SetPinnedRequest
	(*SetMutedRequest)(nil),                       // 8: anychat.conversation.SetMutedRequest
	(*ClearUnreadRequest)(nil),                    // 9: anychat.conversation.ClearUnreadRequest
	(*GetTotalUnreadRequest)(nil),                 // 10: anychat.conversation.GetTotalUnreadRequest
	(*GetTotalUnreadResponse)(nil),                // 11: anychat.conversation.GetTotalUnreadResponse
	(*IncrUnreadRequest)(nil),                     // 12: anychat.conversation.IncrUnreadRequest
	(*SetBurnAfterReadingRequest)(nil),            // 13: anychat.conversation.SetBurnAfterReadingRequest
	(*SetAutoDeleteRequest)(nil),                  // 14: anychat.conversation.SetAutoDeleteRequest
	(*timestamp.Timestamp)(nil),                   // 15: google.protobuf.Timestamp
	(*common.Empty)(nil),                          // 16: anychat.common.Empty
}
var file_conversation_conversation_proto_depIdxs = []int32{
	15, // 0: anychat.conversation.Conversation.last_message_time:type_name -> google.protobuf.Timestamp
	15, // 1: anychat.conversation.Conversation.pin_time:type_name -> google.protobuf.Timestamp
	15, // 2: anychat.conversation.Conversation.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: anychat.conversation.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: anychat.conversation.GetConversationsResponse.conversations:type_name -> anychat.conversation.Conversation
	1,  // 5: anychat.conversation.ConversationService.GetConversations:input_type -> anychat.conversation.GetConversationsRequest
	3,  // 6: anychat.conversation.ConversationService.GetConversation:input_type -> anychat.conversation.GetConversationRequest
	5,  // 7: anychat.conversation.ConversationService.CreateOrUpdateConversation:input_type -> anychat.conversation.CreateOrUpdateConversationRequest
	6,  // 8: anychat.conversation.ConversationService.DeleteConversation:input_type -> anychat.conversation.DeleteConversationRequest
	7,  // 9: anychat.conversation.ConversationService.SetPinned:input_type -> anychat.conversation.SetPinnedRequest
	8,  // 10: anychat.conversation.ConversationService.SetMuted:input_type -> anychat.conversation.SetMutedRequest
	9,  // 11: anychat.conversation.ConversationService.ClearUnread:input_type -> anychat.conversation.ClearUnreadRequest
	10, // 12: anychat.conversation.ConversationService.GetTotalUnread:input_type -> anychat.conversation.GetTotalUnreadRequest
	12, // 13: anychat.conversation.ConversationService.IncrUnread:input_type -> anychat.conversation.IncrUnreadRequest
	13, // 14: anychat.conversation.ConversationService.SetBurnAfterReading:input_type -> anychat.conversation.SetBurnAfterReadingRequest
	14, // 15: anychat.conversation.ConversationService.SetAutoDelete:input_type -> anychat.conversation.SetAutoDeleteRequest
	2,  // 16: anychat.conversation.ConversationService.GetConversations:output_type -> anychat.conversation.GetConversationsResponse
	0,  // 17: anychat.conversation.ConversationService.GetConversation:output_type -> anychat.conversation.Conversation
	0,  // 18: anychat.conversation.ConversationService.CreateOrUpdateConversation:output_type -> anychat.conversation.Conversation
	16, // 19: anychat.conversation.ConversationService.DeleteConversation:output_type -> anychat.common.Empty
	16, // 20: anychat.conversation.ConversationService.SetPinned:output_type -> anychat.common.Empty
	16, // 21: anychat.conversation.ConversationService.SetMuted:output_type -> anychat.common.Empty
	16, // 22: anychat.conversation.ConversationService.ClearUnread:output_type -> anychat.common.Empty
	11, // 23: anychat.conversation.ConversationService.GetTotalUnread:output_type -> anychat.conversation.GetTotalUnreadResponse
	16, // 24: anychat.conversation.ConversationService.IncrUnread:output_type -> anychat.common.Empty
	16, // 25: anychat.conversation.ConversationService.SetBurnAfterReading:output_type -> anychat.common.Empty
	16, // 26: anychat.conversation.ConversationService.SetAutoDelete:output_type -> anychat.common.Empty
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_conversation_conversation_proto_init() }
func file_conversation_conversation_proto_init() {
	if File_conversation_conversation_proto != nil {
		return
	}
	file_conversation_conversation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_conversation_proto_msgTypes,
	}.Build()
	File_conversation_conversation_proto = out.File
	file_conversation_conversation_proto_goTypes = nil
	file_conversation_conversation_proto_depIdxs = nil
}
