// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: file/file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileType 文件类型
type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_IMAGE       FileType = 1
	FileType_FILE_TYPE_VIDEO       FileType = 2
	FileType_FILE_TYPE_AUDIO       FileType = 3
	FileType_FILE_TYPE_FILE        FileType = 4
	FileType_FILE_TYPE_LOG         FileType = 5
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_IMAGE",
		2: "FILE_TYPE_VIDEO",
		3: "FILE_TYPE_AUDIO",
		4: "FILE_TYPE_FILE",
		5: "FILE_TYPE_LOG",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_IMAGE":       1,
		"FILE_TYPE_VIDEO":       2,
		"FILE_TYPE_AUDIO":       3,
		"FILE_TYPE_FILE":        4,
		"FILE_TYPE_LOG":         5,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_file_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_file_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{0}
}

// FileStatus 文件状态
type FileStatus int32

const (
	FileStatus_FILE_STATUS_DELETED    FileStatus = 0
	FileStatus_FILE_STATUS_ACTIVE     FileStatus = 1
	FileStatus_FILE_STATUS_PROCESSING FileStatus = 2
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_DELETED",
		1: "FILE_STATUS_ACTIVE",
		2: "FILE_STATUS_PROCESSING",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_DELETED":    0,
		"FILE_STATUS_ACTIVE":     1,
		"FILE_STATUS_PROCESSING": 2,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_file_file_proto_enumTypes[1].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_file_file_proto_enumTypes[1]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{1}
}

// UploadStatus 分片上传状态
type UploadStatus int32

const (
	UploadStatus_UPLOAD_STATUS_UNSPECIFIED UploadStatus = 0
	UploadStatus_UPLOAD_STATUS_PENDING     UploadStatus = 1
	UploadStatus_UPLOAD_STATUS_UPLOADING   UploadStatus = 2
	UploadStatus_UPLOAD_STATUS_COMPLETED   UploadStatus = 3
	UploadStatus_UPLOAD_STATUS_FAILED      UploadStatus = 4
)

// Enum value maps for UploadStatus.
var (
	UploadStatus_name = map[int32]string{
		0: "UPLOAD_STATUS_UNSPECIFIED",
		1: "UPLOAD_STATUS_PENDING",
		2: "UPLOAD_STATUS_UPLOADING",
		3: "UPLOAD_STATUS_COMPLETED",
		4: "UPLOAD_STATUS_FAILED",
	}
	UploadStatus_value = map[string]int32{
		"UPLOAD_STATUS_UNSPECIFIED": 0,
		"UPLOAD_STATUS_PENDING":     1,
		"UPLOAD_STATUS_UPLOADING":   2,
		"UPLOAD_STATUS_COMPLETED":   3,
		"UPLOAD_STATUS_FAILED":      4,
	}
)

func (x UploadStatus) Enum() *UploadStatus {
	p := new(UploadStatus)
	*p = x
	return p
}

func (x UploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_file_file_proto_enumTypes[2].Descriptor()
}

func (UploadStatus) Type() protoreflect.EnumType {
	return &file_file_file_proto_enumTypes[2]
}

func (x UploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus.Descriptor instead.
func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{2}
}

// FileInfo 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      FileType               `protobuf:"varint,4,opt,name=file_type,json=fileType,proto3,enum=file.FileType" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	StoragePath   string                 `protobuf:"bytes,7,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	ThumbnailPath string                 `protobuf:"bytes,8,opt,name=thumbnail_path,json=thumbnailPath,proto3" json:"thumbnail_path,omitempty"`
	BucketName    string                 `protobuf:"bytes,9,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Status        FileStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=file.FileStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *int64                 `protobuf:"varint,12,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	Metadata      *string                `protobuf:"bytes,13,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"` // JSON string
	DownloadUrl   *string                `protobuf:"bytes,14,opt,name=download_url,json=downloadUrl,proto3,oneof" json:"download_url,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,15,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *FileInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileInfo) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *FileInfo) GetThumbnailPath() string {
	if x != nil {
		return x.ThumbnailPath
	}
	return ""
}

func (x *FileInfo) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *FileInfo) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_DELETED
}

func (x *FileInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileInfo) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *FileInfo) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *FileInfo) GetDownloadUrl() string {
	if x != nil && x.DownloadUrl != nil {
		return *x.DownloadUrl
	}
	return ""
}

func (x *FileInfo) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

// GenerateUploadTokenRequest 生成上传凭证请求
type GenerateUploadTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileType      FileType               `protobuf:"varint,5,opt,name=file_type,json=fileType,proto3,enum=file.FileType" json:"file_type,omitempty"`
	ExpiresHours  *int32                 `protobuf:"varint,6,opt,name=expires_hours,json=expiresHours,proto3,oneof" json:"expires_hours,omitempty"` // 文件过期时间（小时），0表示永不过期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadTokenRequest) Reset() {
	*x = GenerateUploadTokenRequest{}
	mi := &file_file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadTokenRequest) ProtoMessage() {}

func (x *GenerateUploadTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateUploadTokenRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUploadTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateUploadTokenRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GenerateUploadTokenRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GenerateUploadTokenRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateUploadTokenRequest) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *GenerateUploadTokenRequest) GetExpiresHours() int32 {
	if x != nil && x.ExpiresHours != nil {
		return *x.ExpiresHours
	}
	return 0
}

// GenerateUploadTokenResponse 生成上传凭证响应
type GenerateUploadTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // URL有效期（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadTokenResponse) Reset() {
	*x = GenerateUploadTokenResponse{}
	mi := &file_file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadTokenResponse) ProtoMessage() {}

func (x *GenerateUploadTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateUploadTokenResponse) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateUploadTokenResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GenerateUploadTokenResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// CompleteUploadRequest 完成上传请求
type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CompleteUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GenerateDownloadURLRequest 生成下载链接请求
type GenerateDownloadURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresMinutes *int32                 `protobuf:"varint,3,opt,name=expires_minutes,json=expiresMinutes,proto3,oneof" json:"expires_minutes,omitempty"` // URL有效期（分钟），默认60分钟
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateDownloadURLRequest) Reset() {
	*x = GenerateDownloadURLRequest{}
	mi := &file_file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLRequest) ProtoMessage() {}

func (x *GenerateDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDownloadURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GenerateDownloadURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateDownloadURLRequest) GetExpiresMinutes() int32 {
	if x != nil && x.ExpiresMinutes != nil {
		return *x.ExpiresMinutes
	}
	return 0
}

// GenerateDownloadURLResponse 生成下载链接响应
type GenerateDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // URL有效期（秒）
	ThumbnailUrl  *string                `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDownloadURLResponse) Reset() {
	*x = GenerateDownloadURLResponse{}
	mi := &file_file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLResponse) ProtoMessage() {}

func (x *GenerateDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateDownloadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GenerateDownloadURLResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GenerateDownloadURLResponse) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

// GetFileInfoRequest 获取文件信息请求
type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileInfoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetFileInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteFileRequest 删除文件请求
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DeleteFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteFileResponse 删除文件响应
type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListUserFilesRequest 列出用户文件请求
type ListUserFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileType      *FileType              `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3,enum=file.FileType,oneof" json:"file_type,omitempty"` // 可选：按文件类型过滤
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFilesRequest) Reset() {
	*x = ListUserFilesRequest{}
	mi := &file_file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesRequest) ProtoMessage() {}

func (x *ListUserFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesRequest.ProtoReflect.Descriptor instead.
func (*ListUserFilesRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserFilesRequest) GetFileType() FileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *ListUserFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListUserFilesResponse 列出用户文件响应
type ListUserFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFilesResponse) Reset() {
	*x = ListUserFilesResponse{}
	mi := &file_file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesResponse) ProtoMessage() {}

func (x *ListUserFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesResponse.ProtoReflect.Descriptor instead.
func (*ListUserFilesResponse) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListUserFilesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserFilesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserFilesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// BatchGetFileInfoRequest 批量获取文件信息请求
type BatchGetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []string               `protobuf:"bytes,1,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFileInfoRequest) Reset() {
	*x = BatchGetFileInfoRequest{}
	mi := &file_file_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFileInfoRequest) ProtoMessage() {}

func (x *BatchGetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchGetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetFileInfoRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *BatchGetFileInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// BatchGetFileInfoResponse 批量获取文件信息响应
type BatchGetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFileInfoResponse) Reset() {
	*x = BatchGetFileInfoResponse{}
	mi := &file_file_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFileInfoResponse) ProtoMessage() {}

func (x *BatchGetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*BatchGetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_file_file_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetFileInfoResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_file_file_proto protoreflect.FileDescriptor

const file_file_file_proto_rawDesc = "" +
	"\n" +
	"\x0ffile/file.proto\x12\x04file\"\xca\x04\n" +
	"\bFileInfo\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12+\n" +
	"\tfile_type\x18\x04 \x01(\x0e2\x0e.file.FileTypeR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12!\n" +
	"\fstorage_path\x18\a \x01(\tR\vstoragePath\x12%\n" +
	"\x0ethumbnail_path\x18\b \x01(\tR\rthumbnailPath\x12\x1f\n" +
	"\vbucket_name\x18\t \x01(\tR\n" +
	"bucketName\x12(\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x10.file.FileStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\"\n" +
	"\n" +
	"expires_at\x18\f \x01(\x03H\x00R\texpiresAt\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\r \x01(\tH\x01R\bmetadata\x88\x01\x01\x12&\n" +
	"\fdownload_url\x18\x0e \x01(\tH\x02R\vdownloadUrl\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x0f \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01B\r\n" +
	"\v_expires_atB\v\n" +
	"\t_metadataB\x0f\n" +
	"\r_download_urlB\x10\n" +
	"\x0e_thumbnail_url\"\xf5\x01\n" +
	"\x1aGenerateUploadTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12+\n" +
	"\tfile_type\x18\x05 \x01(\x0e2\x0e.file.FileTypeR\bfileType\x12(\n" +
	"\rexpires_hours\x18\x06 \x01(\x05H\x00R\fexpiresHours\x88\x01\x01B\x10\n" +
	"\x0e_expires_hours\"t\n" +
	"\x1bGenerateUploadTokenResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"I\n" +
	"\x15CompleteUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x90\x01\n" +
	"\x1aGenerateDownloadURLRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x0fexpires_minutes\x18\x03 \x01(\x05H\x00R\x0eexpiresMinutes\x88\x01\x01B\x12\n" +
	"\x10_expires_minutes\"\x9b\x01\n" +
	"\x1bGenerateDownloadURLResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\x12(\n" +
	"\rthumbnail_url\x18\x03 \x01(\tH\x00R\fthumbnailUrl\x88\x01\x01B\x10\n" +
	"\x0e_thumbnail_url\"F\n" +
	"\x12GetFileInfoRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"E\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa0\x01\n" +
	"\x14ListUserFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\tfile_type\x18\x02 \x01(\x0e2\x0e.file.FileTypeH\x00R\bfileType\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\f\n" +
	"\n" +
	"_file_type\"\x84\x01\n" +
	"\x15ListUserFilesResponse\x12$\n" +
	"\x05files\x18\x01 \x03(\v2\x0e.file.FileInfoR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"M\n" +
	"\x17BatchGetFileInfoRequest\x12\x19\n" +
	"\bfile_ids\x18\x01 \x03(\tR\afileIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x18BatchGetFileInfoResponse\x12$\n" +
	"\x05files\x18\x01 \x03(\v2\x0e.file.FileInfoR\x05files*\x8b\x01\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFILE_TYPE_IMAGE\x10\x01\x12\x13\n" +
	"\x0fFILE_TYPE_VIDEO\x10\x02\x12\x13\n" +
	"\x0fFILE_TYPE_AUDIO\x10\x03\x12\x12\n" +
	"\x0eFILE_TYPE_FILE\x10\x04\x12\x11\n" +
	"\rFILE_TYPE_LOG\x10\x05*Y\n" +
	"\n" +
	"FileStatus\x12\x17\n" +
	"\x13FILE_STATUS_DELETED\x10\x00\x12\x16\n" +
	"\x12FILE_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16FILE_STATUS_PROCESSING\x10\x02*\x9c\x01\n" +
	"\fUploadStatus\x12\x1d\n" +
	"\x19UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15UPLOAD_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17UPLOAD_STATUS_UPLOADING\x10\x02\x12\x1b\n" +
	"\x17UPLOAD_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14UPLOAD_STATUS_FAILED\x10\x042\x9b\x04\n" +
	"\vFileService\x12Z\n" +
	"\x13GenerateUploadToken\x12 .file.GenerateUploadTokenRequest\x1a!.file.GenerateUploadTokenResponse\x12=\n" +
	"\x0eCompleteUpload\x12\x1b.file.CompleteUploadRequest\x1a\x0e.file.FileInfo\x12Z\n" +
	"\x13GenerateDownloadURL\x12 .file.GenerateDownloadURLRequest\x1a!.file.GenerateDownloadURLResponse\x127\n" +
	"\vGetFileInfo\x12\x18.file.GetFileInfoRequest\x1a\x0e.file.FileInfo\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.file.DeleteFileRequest\x1a\x18.file.DeleteFileResponse\x12H\n" +
	"\rListUserFiles\x12\x1a.file.ListUserFilesRequest\x1a\x1b.file.ListUserFilesResponse\x12Q\n" +
	"\x10BatchGetFileInfo\x12\x1d.file.BatchGetFileInfoRequest\x1a\x1e.file.BatchGetFileInfoResponseB/Z-github.com/anychat/server/api/proto/file;fileb\x06proto3"

var (
	file_file_file_proto_rawDescOnce sync.Once
	file_file_file_proto_rawDescData []byte
)

func file_file_file_proto_rawDescGZIP() []byte {
	file_file_file_proto_rawDescOnce.Do(func() {
		file_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_file_proto_rawDesc), len(file_file_file_proto_rawDesc)))
	})
	return file_file_file_proto_rawDescData
}

var file_file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_file_file_proto_goTypes = []any{
	(FileType)(0),                       // 0: file.FileType
	(FileStatus)(0),                     // 1: file.FileStatus
	(UploadStatus)(0),                   // 2: file.UploadStatus
	(*FileInfo)(nil),                    // 3: file.FileInfo
	(*GenerateUploadTokenRequest)(nil),  // 4: file.GenerateUploadTokenRequest
	(*GenerateUploadTokenResponse)(nil), // 5: file.GenerateUploadTokenResponse
	(*CompleteUploadRequest)(nil),       // 6: file.CompleteUploadRequest
	(*GenerateDownloadURLRequest)(nil),  // 7: file.GenerateDownloadURLRequest
	(*GenerateDownloadURLResponse)(nil), // 8: file.GenerateDownloadURLResponse
	(*GetFileInfoRequest)(nil),          // 9: file.GetFileInfoRequest
	(*DeleteFileRequest)(nil),           // 10: file.DeleteFileRequest
	(*DeleteFileResponse)(nil),          // 11: file.DeleteFileResponse
	(*ListUserFilesRequest)(nil),        // 12: file.ListUserFilesRequest
	(*ListUserFilesResponse)(nil),       // 13: file.ListUserFilesResponse
	(*BatchGetFileInfoRequest)(nil),     // 14: file.BatchGetFileInfoRequest
	(*BatchGetFileInfoResponse)(nil),    // 15: file.BatchGetFileInfoResponse
}
var file_file_file_proto_depIdxs = []int32{
	0,  // 0: file.FileInfo.file_type:type_name -> file.FileType
	1,  // 1: file.FileInfo.status:type_name -> file.FileStatus
	0,  // 2: file.GenerateUploadTokenRequest.file_type:type_name -> file.FileType
	0,  // 3: file.ListUserFilesRequest.file_type:type_name -> file.FileType
	3,  // 4: file.ListUserFilesResponse.files:type_name -> file.FileInfo
	3,  // 5: file.BatchGetFileInfoResponse.files:type_name -> file.FileInfo
	4,  // 6: file.FileService.GenerateUploadToken:input_type -> file.GenerateUploadTokenRequest
	6,  // 7: file.FileService.CompleteUpload:input_type -> file.CompleteUploadRequest
	7,  // 8: file.FileService.GenerateDownloadURL:input_type -> file.GenerateDownloadURLRequest
	9,  // 9: file.FileService.GetFileInfo:input_type -> file.GetFileInfoRequest
	10, // 10: file.FileService.DeleteFile:input_type -> file.DeleteFileRequest
	12, // 11: file.FileService.ListUserFiles:input_type -> file.ListUserFilesRequest
	14, // 12: file.FileService.BatchGetFileInfo:input_type -> file.BatchGetFileInfoRequest
	5,  // 13: file.FileService.GenerateUploadToken:output_type -> file.GenerateUploadTokenResponse
	3,  // 14: file.FileService.CompleteUpload:output_type -> file.FileInfo
	8,  // 15: file.FileService.GenerateDownloadURL:output_type -> file.GenerateDownloadURLResponse
	3,  // 16: file.FileService.GetFileInfo:output_type -> file.FileInfo
	11, // 17: file.FileService.DeleteFile:output_type -> file.DeleteFileResponse
	13, // 18: file.FileService.ListUserFiles:output_type -> file.ListUserFilesResponse
	15, // 19: file.FileService.BatchGetFileInfo:output_type -> file.BatchGetFileInfoResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_file_file_proto_init() }
func file_file_file_proto_init() {
	if File_file_file_proto != nil {
		return
	}
	file_file_file_proto_msgTypes[0].OneofWrappers = []any{}
	file_file_file_proto_msgTypes[1].OneofWrappers = []any{}
	file_file_file_proto_msgTypes[4].OneofWrappers = []any{}
	file_file_file_proto_msgTypes[5].OneofWrappers = []any{}
	file_file_file_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_file_proto_rawDesc), len(file_file_file_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_file_proto_goTypes,
		DependencyIndexes: file_file_file_proto_depIdxs,
		EnumInfos:         file_file_file_proto_enumTypes,
		MessageInfos:      file_file_file_proto_msgTypes,
	}.Build()
	File_file_file_proto = out.File
	file_file_file_proto_goTypes = nil
	file_file_file_proto_depIdxs = nil
}
